#!/bin/sh
#---------------------------------------------------------------
# Project         : Mandriva Linux
# Module          : s2u
# File            : hostname-post
# Version         : $Id$
# Author          : Frederic Lepied
# Created On      : Tue Jul  6 16:10:03 2004
# Purpose         : send a dbus message on hostname change to all
#                 running X11 dbus session.
#---------------------------------------------------------------

dbus-send --system --type=signal /com/mandriva/user com.mandriva.user.message string:"Hostname: $1"

# hostname-post ends here
