#############################################################################
# File		: Makefile
# Package	: s2u
# Author	: Frederic Lepied
# Created on	: Mon Sep 30 13:20:18 1999
# Version	: $Id$
# Purpose	: rules to manage the files.
#############################################################################

PACKAGE=s2u
VERSION:=$(shell rpm -q --qf '%{VERSION}\n' --specfile $(PACKAGE).spec | head -1)
RELEASE:=$(shell rpm -q --qf '%{RELEASE}\n' --specfile $(PACKAGE).spec | head -1)
TAG := $(shell echo "V$(VERSION)_$(RELEASE)" | tr -- '-.' '__')

FILES = Makefile README hostname-post s2u.c s2u.sh s2u.spec \
 AUTHORS LICENSE README ChangeLog s2u.conf

DEFS = -DDBUS_API_SUBJECT_TO_CHANGE=1
CC = gcc
CFLAGS = -O2 -pipe -Wall -Werror
INCLUDES = $(shell pkg-config dbus-glib-1 gdk-2.0 --cflags)
LDFLAGS =  $(shell pkg-config dbus-glib-1 gdk-2.0 --libs)

COMPILE = $(CC) $(DEFS) $(CFLAGS)

all: s2u

s2u:	s2u.o
	$(CC) $(LDFLAGS) -o $@ $^

.c.o:
	$(COMPILE) $(INCLUDES) -c $<

clean:			
	rm -f *.o s2u *~

install:
	install -d $(DESTDIR)/etc/X11/xinit.d
	install s2u.sh $(DESTDIR)/etc/X11/xinit.d
	install -d $(DESTDIR)/usr/bin
	install s2u $(DESTDIR)/usr/bin
	install -d $(DESTDIR)/etc/sysconfig/network-scripts/hostname.d
	install hostname-post $(DESTDIR)/etc/sysconfig/network-scripts/hostname.d/s2u
	install -d $(DESTDIR)/etc/dbus-1/system.d
	install -m 644 s2u.conf $(DESTDIR)/etc/dbus-1/system.d

# rules to build a test rpm

localrpm: localdist buildrpm

localdist: cleandist dir localcopy tar

cleandist:
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.bz2

dir:
	mkdir $(PACKAGE)-$(VERSION)

localcopy:
	tar c $(FILES) | tar x -C $(PACKAGE)-$(VERSION)

tar:
	tar cvf $(PACKAGE)-$(VERSION).tar $(PACKAGE)-$(VERSION)
	bzip2 -9vf $(PACKAGE)-$(VERSION).tar
	rm -rf $(PACKAGE)-$(VERSION)

buildrpm:
	rpm -ta $(PACKAGE)-$(VERSION).tar.bz2

# rules to build a distributable rpm

rpm: changelog cvstag dist buildrpm

dist: cleandist dir export tar

export:
	cvs export -d $(PACKAGE)-$(VERSION) -r $(TAG) $(PACKAGE)

cvstag:
	cvs tag $(CVSTAGOPT) $(TAG)

changelog: ../common/username
	cvs2cl -U ../common/username -I ChangeLog 
	rm -f ChangeLog.bak
	cvs commit -m "Generated by cvs2cl the `date '+%d_%b'`" ChangeLog

# Makefile ends here
