#############################################################################
# File		: Makefile
# Package	: s2u
# Author	: Frederic Lepied
# Created on	: Mon Sep 30 13:20:18 1999
# Version	: $Id$
# Purpose	: rules to manage the files.
#############################################################################

PACKAGE=s2u
TAG := $(shell echo "V$(VERSION)_$(RELEASE)" | tr -- '-.' '__')
SVNROOT = svn+ssh://svn.mandriva.com/svn/soft/$(PACKAGE)


FILES = Makefile README hostname-post s2u.c s2u.sh \
 AUTHORS LICENSE README ChangeLog s2u.conf

DEFS = -DDBUS_API_SUBJECT_TO_CHANGE=1
CC = gcc
CFLAGS = -O2 -pipe -Wall -Werror
INCLUDES = $(shell pkg-config dbus-glib-1 gdk-2.0 --cflags)
LDFLAGS =  $(shell pkg-config dbus-glib-1 gdk-2.0 --libs)

COMPILE = $(CC) $(DEFS) $(CFLAGS)

all: s2u

s2u:	s2u.o
	$(CC) $(LDFLAGS) -o $@ $^

.c.o:
	$(COMPILE) $(INCLUDES) -c $<

clean:			
	rm -f *.o s2u *~

install:
	install -d $(DESTDIR)/etc/X11/xinit.d
	install s2u.sh $(DESTDIR)/etc/X11/xinit.d/s2u
	install -d $(DESTDIR)/usr/bin
	install s2u $(DESTDIR)/usr/bin
	install -d $(DESTDIR)/etc/sysconfig/network-scripts/hostname.d
	install hostname-post $(DESTDIR)/etc/sysconfig/network-scripts/hostname.d/s2u
	install -d $(DESTDIR)/etc/dbus-1/system.d
	install -m 644 s2u.conf $(DESTDIR)/etc/dbus-1/system.d

# rules to build a test rpm
checktag:
	@if [ "x$(VERSION)" == "x" -o "x$(RELEASE)" = "x" ]; then \
 	  echo usage is "make VERSION=version_number RELEASE=release_number dist" ; \
	  exit 1 ; \
	fi


localdist: cleandist dir localcopy tar

cleandist: checktag
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.bz2

dir: checktag
	mkdir $(PACKAGE)-$(VERSION)

localcopy: checktag
	tar c $(FILES) | tar x -C $(PACKAGE)-$(VERSION)

tar: checktag
	tar cvf $(PACKAGE)-$(VERSION).tar $(PACKAGE)-$(VERSION)
	bzip2 -9vf $(PACKAGE)-$(VERSION).tar
	rm -rf $(PACKAGE)-$(VERSION)

# rules to build a distributable rpm

dist: checktag cleandist svntag export tar

export: checktag
	svn export $(SVNROOT)/tags/$(TAG) $(PACKAGE)-$(VERSION)

svntag: checktag 
	svn copy $(SVNROOT)/trunk $(SVNROOT)/tags/$(TAG) -m "$(TAG)"

changelog: ../common/username
#svn2cl is available in our contrib.
	svn2cl --authors ../common/username.xml --accum
	rm -f ChangeLog.bak
	svn commit -m "Generated by svn2cl the `date '+%c'`" ChangeLog

# Makefile ends here
